#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine and install html pages
sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
