#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt  update
sudo apt -y install nginx
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
sed -i '/listen 80 default_server;/a rewrite ^/error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
