#!/usr/bin/env bash
# find out what's keeping your Ubuntu sandbox's Nginx installation from listening on port 80
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080/listen \[::\]:80/" /etc/nginx/sites-enabled/default
service nginx restart
