#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
sed -i "s/listen 8080 default_server;\nlisten [::]:8080 default_server;/listen 80 default_server;\nlisten [::]:80 default_server;" /etc/nginx/sites-enabled/default
service nginx restart
service nginx stop
